# Generated by Django 3.1.4 on 2020-12-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('fullname', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('mobileno', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
