# Generated by Django 3.1.4 on 2020-12-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXIDEAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='mobileno',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='user_register',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
