# Generated by Django 3.1.4 on 2020-12-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXIDEAPPLICATION', '0002_auto_20201221_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='mobileno',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
