# Generated by Django 3.1.4 on 2020-12-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXIDEAPPLICATION', '0003_auto_20201221_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_details',
            fields=[
                ('battery_type', models.CharField(max_length=70)),
                ('serial_no', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=80)),
                ('mobno', models.BigIntegerField()),
                ('address', models.CharField(max_length=150)),
                ('purchase_date', models.CharField(max_length=70)),
                ('maintenance_date', models.CharField(max_length=70)),
                ('expiry_date', models.CharField(max_length=70)),
                ('billno', models.IntegerField()),
                ('pincode', models.CharField(max_length=70)),
                ('price', models.BigIntegerField()),
            ],
        ),
    ]
