# Generated by Django 3.1.5 on 2021-01-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXIDEAPPLICATION', '0005_battery_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery_details',
            name='status',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase_details',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
