# Generated by Django 3.1.5 on 2021-01-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXIDEAPPLICATION', '0006_auto_20210106_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_details',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
